pipeline:
  name: nmccarthy-project-jul-26-ci-cd
  identifier: nmccarthy_project_jul_26_ci_cd
  repo:
    connector: jedicraftGitHub
    name: jedicraft/nmccarthy-project-jul-26
  clone:
    depth: 1
  on:
  - push:
      branches: [main]
  stages:
  - name: test-and-build
    runtime: cloud
    platform:
      os: linux
      arch: arm64
    steps:
    - run:
        container:
          image: node:22
        script: npm ci
    - run-test:
        container:
          image: node:22
        script: npm test
    - run:
        container:
          image: node:22
        script: npm run build
  - name: deploy-gcs
    if: ${{ branch == "main" }}
    runtime: cloud
    platform:
      os: linux
      arch: arm64
    steps:
    - template:
        uses: uploadArtifactsToGCS
        with:
          connector: NMcCarthySandboxGCP
          bucket: nmccarthy-project-jul-26-static
          source: dist/**
